### ISSUE TITLE
Definir o DER inicial

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#1]
Criar o DER contendo suporte para a manutenção das informações a seguir:

- **Questões**: descrição da questão, 4 opções cada e uma opção sendo a correta, dica da resposta correta

**Comment by lucasrd2k** [comment]
Boa noite professor, fiz como sugeriu, mas deixei a chave estrangeira de "correta" como null em questões, já que antes de cadastrar as questões, não vai haver perguntas. Vou adicionar à pasta, e fechar aqui.
![image](https://user-images.githubusercontent.com/86005352/191389089-5bd94358-d4fa-4be8-bf12-afe11d403235.png)

**Comment by Ronneesley** [comment]
Favor mudar:

- O nível para ser inteiro
- A descrição da opção e da questão para comportar mais caracteres, tipo texto (text)

**Comment by lucasrd2k** [comment]
![image](https://user-images.githubusercontent.com/86005352/192586356-bb30831c-a750-49a2-8a10-930754a101db.png)

A chave estrangeira não pôde ser colocada na tabela de questões

-- Não tem como criar uma tabela com chave estrangeira de uma tabela ainda não criada
-- Tentei usando o Alter pra adicionar a chave
-- ALTER TABLE questoes ADD FOREIGN KEY (correta) REFERENCES respostas(id);
-- A inclusão da chave estrangeira não é permitida mesmo após a criação das duas tabelas
-- Error Code: 1005. Can't create table `espigao`.`questoes` (errno: 150 "Foreign key constraint is incorrectly formed")
-- Por isso retirei a chave, o funcionamento permanece o mesmo

**Comment by Ronneesley** [comment]
Favor mudar o campo *descricao* das **opcoes** para o tipo *Text*.
Alterar o diagrama e exportar o novo SQL.

**Comment by lucasrd2k** [comment]
der atualizado, sql já tava ok
