### ISSUE TITLE
Criar o projeto inicial usando Spring e o STS

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#2]
Criar o projeto inicial pelo site ou pelo software.

Definir a classe de **Questões** e **Opções** com acesso ao *Java Persistence API (JPA)*.

**Comment by MateusLopesNunes** [comment]
ok

**Comment by Ronneesley** [comment]
Conversar com #1

**Comment by Ronneesley** [comment]
Atualizar a versão para a última versão do Spring 2.7.3

**Comment by Ronneesley** [comment]
Feito
