### ISSUE TITLE
Criar o Dockerfile para o projeto Java com Spring

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#21]
Criar o Dockerfile para subir o projeto Java com Spring.

Criar um container do zero com a imagem: https://hub.docker.com/_/alpine.
Visto que as imagens oficiais do Java estão em desuso.

Baixar e instalar o [Java oficial da Oracle](https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.tar.gz) na imagem e instalá-lo.

Em seguida rodar o arquivo JAR.

**Comment by GuiAlencar** [comment]
Ok

**Comment by Ronneesley** [comment]
Nome do diretório ao extrair: **jdk-19.0.1**

**Comment by Ronneesley** [comment]
Aberto para auxílio técnico

**Comment by Ronneesley** [comment]
Feita
