### ISSUE TITLE
Baixar sons parecidos com o do show do milhão

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#23]
Encontrar sons RoaltyFree para colocar no aplicativo representando os seguintes momentos:

1. Exibição da questão;
2. Questão certa;
3. Questão errada;
4. Momento de tensão antes de aprensentar a resposta;
5. Música para a vitória (ganhar 1 milhão);
6. Música para a desistência;
7. Música de background para a tela inicial;
8. Sons para o tempo acabar (Tick taque do relógio);
9. Som para seleção de uma opção (seleção);
10. Som para eliminação de duas questões (opção de ajuda);
11. Som para pular a questão (opção de ajuda);
12. Som para votação da plateia (opção de ajuda);
13. Som para votação dos universitários  (opção de ajuda);

A pessoa poderá gravar o audio para a situação.

Os áudios deverão estar em MP3 e deverão ser colocados no local correto do projeto Android.
Seguir a [vídeo aula de configuração de MP3](https://www.youtube.com/watch?v=4hw8-jJ6QFo&list=PLzvuv66CWaRfK_xBZWdlIUOpgcDt0TAnO&index=12).

Mostrar um exemplo funcionando de um dos áudios no projeto Android.

**Comment by marcosadf** [comment]
Peguei as opções 1, 2, 3

**Comment by Geovannakerolyn** [comment]
4,5,6

**Comment by Pauloh789** [comment]
Fiquei com a 10, 11 e 12.

**Comment by Ronneesley** [comment]
Renomear: Questao errada para questao_errada

**Comment by Ronneesley** [comment]
Feito
