### ISSUE TITLE
Protótipo da tela de login

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#3]
Fazer uma tela de login pedindo apenas o nome do usuário

**Comment by Pedrofd2k** [comment]
No caso pedir o nome de usuário e salvar localmente com sqLite?

**Comment by Pedrofd2k** [comment]
Ok

**Comment by gothboyclick** [comment]
Trocar a fonte para Nunito por favor

**Comment by Pedrofd2k** [comment]
Feito
