### ISSUE TITLE
Pesquisa: Login com a conta Google

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#30]
Fazer um pequeno exemplo de autenticação de aplicativo com a conta Google.

Provável fonte de exemplos oficiais:
https://developers.google.com/identity/sign-in/web/sign-in

Apresentar o que é preciso para fazer o processo e quais registros.

**Comment by Pauloh789** [comment]
ok

**Comment by Pauloh789** [comment]
https://www.alura.com.br/artigos/autenticando-no-google-com-firebase-authentication 
Material de apoio encontrado na plataforma da Alura.

**Comment by Ronneesley** [comment]
Feito. Problemas burocráticos relacionados ao registro com o Google. Avaliar para implementações futuras.
