### ISSUE TITLE
Correção do DER

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#36]
- [x] Mudar o nome da tabela **usuario** para **usuarios**
- [x] O campo *senha* deve ter 32 caracteres
- [x] Mudar o nome da tabela **pontuacao** para **pontuacoes**
- [x] O campo usuário é obrigatório na tabela de pontuações
- [x] Mudar o tipo do campo **descricao** na tabela **opcoes** para o tipo TEXT

Exportar o Script de criação no final e o DER em PNG

**Comment by MateusLopesNunes** [comment]
eu fui o primeiro

**Comment by Ronneesley** [comment]
Feito
