### ISSUE TITLE
Criar o protótipo do cadastro de Questões Web

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#39]

**Comment by Pauloh789** [comment]
ok

**Comment by Ronneesley** [comment]
O protótipo não comporta o nível da questão. Quando referimos a nível, estamos falando em que prêmio essa questão aparecerá, se é uma questão de R$ 1000, R$ 2000, etc.

**Comment by Ronneesley** [comment]
Feito
