### ISSUE TITLE
Criar o Mock em PHP de resposta correta / incorreta

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#54]
Definir a entrada do quiz, lembrem que tem que chegar os dados: 

- Questão (id)
- Opções e seus (ids)

O resultado em JSON deverá retornar se a resposta está correta ou não, qual resposta era a correta:

Exemplo quando o usuário acerta:
```json
{
   opcao_correta: A
   correta: true
}
```

Exemplo quando o usuário erra:
```json
{
   opcao_correta: C
   correta: false
}
```

**Comment by Geovannakerolyn** [comment]
ENTREGUE!

**Comment by Ronneesley** [comment]
Feito
