### ISSUE TITLE
Fazer a tela do usuário que será apresentada após o login

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#57]
Nesta tela devem haver opções de:

- Iniciar um novo quiz
- Acessar as pontuações
- Sair do sistema

Entregar o protótipo junto.

**Comment by Geovannakerolyn** [comment]
Protótipo entregue!

**Comment by Thiagosn1** [comment]
Protótipo alterado.

**Comment by Thiagosn1** [comment]
Protótipo e tela entregues.

**Comment by Ronneesley** [comment]
Feito
