### ISSUE TITLE
Fazer o estudo das licenças para escolhermos uma delas

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#65]
* GPL
* Apache 
* MIT

Entregar o PDF e o editável na pasta documentos do projeto (se não houver a pasta criar).
Comparando as licenças.

**Comment by Ronneesley** [comment]
Abri pra mais dois. Fazer uma comparação / estudo mais detalhado.

**Comment by Gustavo-Ti** [comment]
Entregue.

**Comment by LeticiaCamargo29** [comment]
Entregue.

**Comment by Ronneesley** [comment]
Feito
