### ISSUE TITLE
Fazer uma tabela das licenças quanto

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#68]
* É permitido vender? (não)
* É permitido usar o sistema? (sim)
* É permitido distribuir o sistema em nome próprio? (não)
* É permitido alterar e distribuir em outra versão? (não)
* É permitido distribuir dando os créditos? (?)

**Comment by LeticiaCamargo29** [comment]
Feito

**Comment by Ronneesley** [comment]
Feito
