### ISSUE TITLE
Protótipo do prêmio atual

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#7]
Fazer uma tela que representa o prêmio atual do usuário. 

Mostrar quanto ele já ganhou e quanto ainda pode ganhar nessa tela.

**Comment by MathMedrado** [comment]
ok

**Comment by gothboyclick** [comment]
afim de unificar mais os protótipos eu recomendo a troca da fonte para Nunito

**Comment by Ronneesley** [comment]
Feito
