### ISSUE TITLE
Criar o banco de dados com 100 questões.

### ISSUE THREAD

**Issue by Ronneesley** [Ronneesley/showdoespigao#9]
Questões temáticas de informática.

Criar o arquivo SQL contendo os comandos **inserts**

ex.:

insert questoes values(1, 'Qual desses é um número primo?')
insert opcoes values(1, 2, '7');
insert opcoes values(2, 1, '8');

Discutir a estrutura com #1

**Comment by marcosadf** [comment]
ok

**Comment by lucasrd2k** [comment]
Boa tarde pessoal, atualizei o modelo e o código do banco, olhar por favor, sobre os inserts, ficaram assim:

INSERT INTO questoes (descricao, nivel) VALUES ("Sobre diagrama de entidade-relacionamento (DER), marque a alternativa que
NÃO apresenta um tipo de entidade", 1); 
INSERT INTO opcoes (questao, descricao) VALUES (1, "Entidade Fraca"),(1, "Entidade Associativa"),(1, "Entidade Agregada"),(1, "Entidade Composta");

UPDATE questoes SET correta = 4 WHERE id = 1;

**Comment by Ronneesley** [comment]
@LeticiaCamargo29 não está fazendo a atividade.

**Comment by Ronneesley** [comment]
Continua atrasado

**Comment by Ronneesley** [comment]
@LeticiaCamargo29 retirada da tarefa

**Comment by Ronneesley** [comment]
@marcosadf substituirá @LeticiaCamargo29 nesta tarefa.

**Comment by Ronneesley** [comment]
Feito
